install:
  - npm install gitbook-cli -g
  - sudo pip install mkdocs
  - sudo pip install ./plugins/bing-search
  - chmod +x scripts/travis.sh
script: 
  - scripts/travis.sh script
after_success: 
  - scripts/travis.sh after_success
branches:
 only:
  - master
  - java-chassis-1.x
