site_name: ServiceComb Java Chassis 开发指南

nav:

- 目录: toc.md
- 概述 : index.md
- 快速入门: start/catalog.md
- 设计选型参考: start/design.md
- 开发服务提供者: build-provider/catalog.md
- 开发服务消费者: build-consumer/catalog.md
- 通用功能开发: general-development/catalog.md

- Transports:
    - REST over Servlet: transports/rest-over-servlet.md
    - REST over Vertx: transports/rest-over-vertx.md
    - Highway: transports/highway-rpc.md
    - HTTP2: transports/http2.md
- 管理注册发现:
    - 注册发现说明: registry/introduction.md
- 管理服务配置:
    - 通用配置说明: config/general-config.md
    - 配置注入机制: config/inject-config.md
- 服务能力开放:
    - 介绍: edge/open-service.md
    - 使用Edge Service做边缘服务: edge/by-servicecomb-sdk.md
    - 使用confd和Nginx做边缘服务: edge/nginx.md
    - 使用zuul做边缘服务: edge/zuul.md
- 服务打包和运行: 
    - 以standalone模式打包: packaging/standalone.md
    - 以WEB容器模式打包: packaging/web-container.md
- 微服务安全: 
    - 使用TLS通信: security/tls.md
    - 使用RSA认证: security/shi-yong-rsa-ren-zheng.md
- 专题文章:
    - 在Spring Boot中使用java chassis: using-java-chassis-in-spring-boot/using-java-chassis-in-spring-boot.md
    - 使用 inspector 模块查看契约: featured-topics/using-inspector.md
    - 新功能介绍系列文章: featured-topics/features.md
    - 升级指导系列文章: featured-topics/upgrading.md
- 处理链参考: 
    - 处理链介绍: references-handlers/intruduction.md
    - 负载均衡: references-handlers/loadbalance.md
    - 路由管理: references-handlers/router.md
    - 隔离熔断容错: references-handlers/bizkeeper.md
    - 公钥认证: references-handlers/publickey.md
- 常用配置项参考:
    - REST Transport Client 配置项: config-reference/rest-transport-client.md
    - Config Center Client 配置项: config-reference/config-center-client.md
    - Service Center Client 配置项: config-reference/service-center-client.md
    - ServiceComb Kie Client 配置项: config-reference/kie-client.md
- 常见问题:
    - 'Q & A' : question-and-answer/question_answer.md
    - 'FAQ' : question-and-answer/faq.md
    - 微服务接口兼容常见问题: question-and-answer/interface-compatibility.md

theme: readthedocs
plugins:
    - search:
          lang: en